- defaultTab: nodes
  description: |-
    Commodities ETL extract USD, EUR and UF values \
      sudo docker run --rm -v /home/bnbiuser/secrets/blocket_db:/app/db-blocket \
                      -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                      -e APP_DB_SECRET=/app/db-secret \
                         containers.mpi-internal.com/yapo/commodities:fix_empty-calls
  executionEnabled: true
  group: DOCKER/GENERAL
  loglevel: DEBUG
  name: COMMODITIES
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notifyAvgDurationThreshold: null
  scheduleEnabled: false
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/commodities:fix_empty-calls
        sudo docker run --rm -v /home/bnbiuser/secrets/blocket_db:/app/db-blocket \
                            -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                            -e APP_DB_SECRET=/app/db-secret \
                              containers.mpi-internal.com/yapo/commodities:fix_empty-calls
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
