- defaultTab: nodes
  description: |-
    sudo docker run -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
      -e APP_DB_SECRET=/app/db-secret \
      containers.mpi-internal.com/yapo/data-user-behavior-scrapper-pi:feat_pi-spider
  executionEnabled: true
  group: SCRAPPER
  loglevel: DEBUG
  name: Scrapping PortalInmobiliario - Inmo
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notifyAvgDurationThreshold: null
  scheduleEnabled: false
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/data-user-behavior-scrapper-pi:feat_pi-spider

        sudo docker run -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/data-user-behavior-scrapper-pi:feat_pi-spider
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
