- defaultTab: nodes
  description: |-
    sudo docker run -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
      -e APP_DB_SECRET=/app/db-secret \
      -e APP_CRAWLERA_SECRET=/app/crawlera-secret \
      containers.mpi-internal.com/yapo/data-user-behavior-scraper-pi-naa:etl_naa-portal
  executionEnabled: true
  group: SCRAPPER
  loglevel: DEBUG
  name: Scrapping PortalInmobiliario - Inmo NAA
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notifyAvgDurationThreshold: null
  scheduleEnabled: false
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/data-user-behavior-scraper-pi-naa:etl_naa-portal

        sudo docker run -v /home/bnbiuser/secrets/dw_db:/app/db-secret -e APP_DB_SECRET=/app/db-secret \
            -e APP_CRAWLERA_SECRET=/app/crawlera-secret containers.mpi-internal.com/yapo/data-user-behavior-scraper-pi-naa:etl_naa-portal
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
