- defaultTab: nodes
  description: |-
      Yapesos report that takes data from \
       datawarehouse, blocketdb and credits-db
  executionEnabled: true
  group: DOCKER/PULSE
  loglevel: DEBUG
  name: Report - Yapesos revenues
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notification:
    onfailure:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name} - Fallo definitivo
    onretryablefailure:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name} - Fallo por reintento
  notifyAvgDurationThreshold: null
  scheduleEnabled: true
  schedule:
    month: '*'
    time:
      hour: '09'
      minute: '0'
      seconds: '0'
    weekday:
      day: FRI
    year: '*'
  retry:
    retry: 3
    delay: 20m
  sequence:
    commands:
    - script: |-
        sudo docker run -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -v /home/bnbiuser/secrets/blocket_db:/app/db-blocket \
                        -v /home/bnbiuser/secrets/credits-db:/app/db-credits \
                        -e APP_DB_SECRET=/app/db-secret \
                        -e APP_BLOCKET_SECRET=/app/db-blocket \
                        -e APP_CREDIT_SECRET=/app/db-credits \
                        containers.mpi-internal.com/yapo/yapesos-report:latest \
                        -deliver_to="carlos.fuentes@adevinta.com,claudia.castro@adevinta.com,data_team@adevinta.com"
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
