version: '3'
 
services:
  app:
    image: ${DOCKER_IMAGE_COMPOSE}
    container_name: ${DOCKER_CONTAINER_NAME}
    expose:
      - "5000"
    environment:
      APP_ZENDESK_SECRET: /app/zendesk-secret
      APP_DB_SECRET: /app/db-secret
    volumes:
      - /Users/luisbarrera/Documents/secrets/bnbiuser:/app/db-secret
      - /Users/luisbarrera/Documents/secrets/zendesk_auth:/app/zendesk-secret
      #- /keys/bnbiuser:/app/db-secret
      #- /keys/zendesk_auth:/app/zendesk-secret